### ISSUE TITLE
+1 праны

### ISSUE THREAD

**Issue by DiceUA** [ArtemDordovskiy/godville_bingo#1]
Автоматический минусатор чужих гласов в дневнике.

**Comment by ArtemDordovskyi** [comment]
```
jQuery('#diary').bind(<% change %>, function(){
  jQuery(this).find('.vote_link:contains("-")').click();
})
```

**Comment by DiceUA** [comment]
Выкатило такое
Uncaught SyntaxError: Unexpected token <
    at Object.InjectedScript._evaluateOn (<anonymous>:878:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:811:34)
    at Object.InjectedScript.evaluate (<anonymous>:667:21)

InjectedScript._evaluateOn @ (program):878
InjectedScript._evaluateAndWrap @ (program):811
InjectedScript.evaluate @ (program):667

**Comment by ArtemDordovskyi** [comment]
:accept:
